arch: ppc64le
jobs:
  include:


    - stage: Perl Language Test
      name: default version
      install: skip
      language: perl
      script: 
        - perl -v
        - cpanm --version
    - name: 5.26 version
      language: perl
      install: skip
      perl: 5.26
      script: 
        - perl -v
        - cpanm --version
    
    - stage: PHP Language Test
      name: default version
      language: php
      script: php --version
    - name: 7.1.9 version
      language: php
      php: 7.1.9
      script: php --version
