arch: ppc64le
jobs:
  include:

    - stage: Ruby Language Test
      name: default version
      language: ruby
      install: skip
      script: 
        - ruby -v
        - gem install bundler
    - name: 3.1 version
      language: ruby
      rvm: 3.1
      install: skip
      script: 
        - ruby -v
        - gem install bundler
