arch: ppc64le
jobs:
  include:

    - stage: DB Test
      name: POSTGRESQL
      service: mysql
      before_script: mysql -e 'CREATE DATABASE myapp_test;'
      script: 
        - mysql --version
        - mysql -e 'SHOW DATABASES;'
