arch: ppc64le
jobs:
  include:
    - stage: Language Test
      name: C
      language: c
      compiler:
        - clang
        - gcc
      script:
        - $CC --version
      
    - name: CPP
      language: cpp
      compiler:
        - clang
        - gcc
        - /opt/at12.0/bin/g++
      script:
        - $CC --version



