arch: ppc64le
jobs:
  include:

    - stage: DB Test
      name: PostgreSQL
      dis: focal
      service: postgresql
      before_script: psql -c 'create database travis_ci_test;' -U postgres
      script:
        - psql --version
        - psql -c 'SELECT datname FROM pg_database;' -U postgres

