arch: ppc64le
jobs:
  include:



    - stage: PHP Language Test
      language: php
      php: 8.0
      script: php --version

    - stage: Python 
      name: 2.7
      language: python
      python: 2.7
      install: skip
      script: 
        - python --version
        - ls -l
    - name: 3.8
      language: python
      python: 3.8
      install: skip
      script: 
        - python --version
        - ls -l
