arch: ppc64le
jobs:
  include:

    - stage: DB Test
      name: mariadb
      addon:
        mariadb: '10.0'
      script:
        - mysql --version
        - mysql -e 'CREATE DATABASE myapp_test;'
        - mysql -e 'SHOW DATABASES;'

