arch: ppc64le
jobs:
  include:

    - stage: Nodejs Language Test
      language: node_js
      node_js: lts/*
      script:
        - npm install -g gulp-cli
        - gulp version

    - stage: JAVA Language Test
      name: JDK8
      language: java
      jdk: openjdk8
      script: 
        - java -version
        - mvn --version
    - name: JDK11
      language: java
      jdk: openjdk11
      script: 
        - java -version
        - mvn --version
    - name: JDK15
      language: java
      jdk: openjdk15
      script: 
        - java -version
        - mvn --version
  
  
    #- stage: C Language Test
    #  name: GCC
    #  language: c
    #  compiler: gcc
    #  script:
    #    - $CC --version
    #- name: CLANG
    #  language: c
    #  compiler: clang
    #  script:
    #    - $CC --version
    #  
    #- stage: CPP Language Test
    #  name: GCC
    #  language: cpp
    #  compiler: gcc
    #  script:
    #    - $CC --version
    #- name: CLANG
    #  language: cpp
    #  compiler: clang
    #  script:
    #    - $CC --version
    #- name: IBM ATC
    #  language: cpp
    #  compiler: /opt/at12.0/bin/g++
    #  env: PATH=/opt/at14.0/bin:/opt/at14.0/sbin:$PATH CMAKE_PREFIX_PATH=/opt/at14.0/
    #  script:
    #    - /opt/at*/bin/g++ --version



